clone_folder: c:\repos\PoshNuGet

build_script:
- ps: $null;

environment:
  psapikey:
    secure: irPGuqa1jY5hJ4pM1qchY4q8VpoLwJ/una1FpQpWysiGh/BKJQwT67LOu8dOq8r7

os: unstable

install:
#  ps: Import-Module -Path $PSScriptRoot;
#  ps: Publish-Module -Name PoshNuGet -ApiKey $env:psapikey;

branches:
  only:
    - master

deploy_script:
- ps: $null;