clone_folder: c:\repos\PoshNuGet
os: Unstable

build_script:
- ps: $null;

environment:
  psapikey:
    secure: bIZZhKIiPOYu4Ya+Fiwzlnphjj6+liXqg9uBUZD9Y61gSWR7kZf78gYV+3gcJouB

# Disable AppVeyor tests
test: off

deploy_script:
- ps: '& .\deploy.ps1'

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))